### ISSUE TITLE
Installation failes: asset js not found

### ISSUE THREAD

**Issue by benhartwich** [alchemy-fr/Phraseanet#3354]
Hi,

I´ve installed phraseanet on debian 10 with nginx and followed your documentation. After the installation seems to be succeeded I got redirected to the login page, but some js and css files are not found. Is your nginx configuration correct?

`Failed to load resource: the server responded with a status of 404 ()
authentication.min.js:1 Failed to load resource: the server responded with a status of 404 ()
modernizr.min.js:1 Failed to load resource: the server responded with a status of 404 ()
authentication.min.js:1 Failed to load resource: the server responded with a status of 404 ()
?f=scripts/apps/login/home/login.js:1 Uncaught ReferenceError: require is not defined
    at ?f=scripts/apps/login/home/login.js:1
authentication.min.css:1 Failed to load resource: the server responded with a status of 404 ()`

What can I do?

**Comment by nmaillat** [comment]
Hi, 
Did you have play the make for assets deployement  ?
You can also try Phraseanet with docker 
Follow step on Phraseanet readme for building Phraseanet images and use
https://github.com/alchemy-fr/phraseanet-docker for run with docker-compose 
Regards

**Comment by benhartwich** [comment]
Problem was, I was missing npm installed at make process. But the make process failes:

`[17:27:55] Error: ENOENT: no such file or directory, stat 'www/bower_components/html5shiv/dist/html5shiv.js'
    at statSync (fs.js:851:3)
    at Array.forEach (<anonymous>)
    at Object.exports.buildJsGroup (/var/www/fotoarchiv/htdocs/phraseanet/resources/gulp/utils.js:19:14)
    at Gulp.<anonymous> (/var/www/fotoarchiv/htdocs/phraseanet/resources/gulp/components/vendors/html5shiv.js:6:18)
    at module.exports (/var/www/fotoarchiv/htdocs/phraseanet/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/fotoarchiv/htdocs/phraseanet/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/fotoarchiv/htdocs/phraseanet/node_modules/orchestrator/index.js:214:10)
    at /var/www/fotoarchiv/htdocs/phraseanet/node_modules/orchestrator/index.js:279:18
    at finish (/var/www/fotoarchiv/htdocs/phraseanet/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/var/www/fotoarchiv/htdocs/phraseanet/node_modules/orchestrator/lib/runTask.js:60:3)
`
