### ISSUE TITLE
Worker throws a "This is not a valid version" fatal error

### ISSUE THREAD

**Issue by bmalynovytch** [alchemy-fr/Phraseanet#3675]
Version: 4.1.2 with Docker

Worker used to be working.
Something changed in the configuration, trying to get #3674 working.
Now, worker keeps crashing with the following error:
```
worker_1         | PHP Fatal error:  Uncaught vierbergenlars\SemVer\SemVerException: This is not a valid version [[]] in /var/alchemy/Phraseanet/vendor/vierbergenlars/php-semver/src/vierbergenlars/SemVer/version.php:24
worker_1         | Stack trace:
worker_1         | #0 /var/alchemy/Phraseanet/vendor/vierbergenlars/php-semver/src/vierbergenlars/SemVer/version.php(167): vierbergenlars\SemVer\version->__construct('0.0.0.0')
worker_1         | #1 /var/alchemy/Phraseanet/vendor/vierbergenlars/php-semver/src/vierbergenlars/SemVer/version.php(248): vierbergenlars\SemVer\version::gt(Object(vierbergenlars\SemVer\version), '0.0.0.0')
worker_1         | #2 /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Setup/ConfigurationTester.php(113): vierbergenlars\SemVer\version::lt('0.0.0.0', '4.1.2')
worker_1         | #3 /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Setup/ConfigurationTester.php(88): Alchemy\Phrasea\Setup\ConfigurationTester->isUpgradable()
worker_1         | #4 /var/alchemy/Phraseanet/bin/console(90): Alchemy\Phrasea\Setup\ConfigurationTester->isUpToDate()
worker_1         | #5 {main}
worker_1         |   thrown in /var/alchemy/Phraseanet/vendor/vierbergenlars/php-semver/src/vierbergenlars/SemVer/version.php on line 24
```

Removing containers & volumes didn't solve the issue.

**Comment by bmalynovytch** [comment]
Deleting the content of the cache directory seems to fix the issue.
