### ISSUE TITLE
MAJ 4.0.2 vers 4.1.3

### ISSUE THREAD

**Issue by pnrm** [alchemy-fr/Phraseanet#3751]
Suite à la mise à jour de la version 4.02 à la version 4.1.3 de Phraseanet je ne peux plus éditer mes photos. Je n'ai pas eu de message d'erreur particuliers à la mise à jour. l'upload fonctionne bien et importe bien les paramètres de la photo.
Si j'ajoute des éléments dans les champs de la photos avec le menu editer et que je valide. 
Les éléments que je saisie ne sont pas pris en compte. 
Mon serveur est sous debian 9 avec php7 et apache2
J'ai le message d'erreur suivant au niveau du worker manager
![image](https://user-images.githubusercontent.com/18323883/111486072-745af080-8737-11eb-95c8-1467a96ea8bf.png)

**Comment by nmaillat** [comment]
Bonjour, 
En version 4.1 Phraseanet require l'utilisation de rabbitMQ pour le fonctionnement de workers.

Les workers Phraseanet prenne et compte un certain nombre de taches qui étaient avant assuré par des taches, lancées au moyen du scheduler.

lors d'une migration d'une version 4.0 vers 4.1 dans certaines condition, la section de configuration de rabbitMQ peux être  absente de la configuration.
Un ticket est ouvert chez nous pour ce problème et un fix est disponible mais pas encore mergé.

Vous pouvez néanmoins ajouter manuellement cette section dans le fichier `config/configuration.yml` et compilé la configuration au moyen de 
`bin/console compile:configuration`

eg: 
```workers:
    queue:
        worker-queue:
            registry: alchemy_worker.queue_registry
            host: localhost
            port: 5672
            user: defineme
            password: defineme
            vhost: /defineme
...

```
Ici un exemple du bloc de la section de configuration a ajouter. 
[https://github.com/alchemy-fr/Phraseanet/blob/master/config/configuration.sample.yml](https://github.com/alchemy-fr/Phraseanet/blob/master/config/configuration.sample.yml)


Si vous utilisé le worker, les taches de fabrication de sous définition et d'écriture de meta données ne devrons pas être utilisé simultanément.
il est recommandé de stopper le lancement du "scheduler"  ou simplement des taches "fabrication de sous définition" et "d'écriture de meta données".

la commande de lancement du worker s'effectue uniquement en console 
`bin/console worker:execute`

l'option `-m` permet de définir le nombre de worker simultané désirer pour chacun des workers 


```
bin/console worker:execute --help
Usage:
  worker:execute [options]

Options:
  -p, --preserve-payload             Preserve temporary payload file
      --queue-name=QUEUE-NAME        The name of queues to be consuming (multiple values allowed)
  -m, --max-processes=MAX-PROCESSES  The max number of process allow to run (default 1) 
  -h, --help                         Display this help message
  -q, --quiet                        Do not output any message
  -V, --version                      Display this application version
      --ansi                         Force ANSI output
      --no-ansi                      Disable ANSI output
  -n, --no-interaction               Do not ask any interactive question
  -v|vv|vvv, --verbose               Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Listen queues define on configuration, launch corresponding service for execution
``

**Comment by pnrm** [comment]
Bonjour,
Merci pour votre retrour
J'ai ajouté dans mon fichier configuration.yml le code suivant
```
workers:
    queue:
        worker-queue:
          registry: alchemy_worker.queue_registry
          host: localhost
          port: 5672
          user: guest
          password: guest
          vhost: /
    queues:
        writeMetadatas:           # this Q is "delayable" in case of record is locked
            ttl_retry: 1500         # overwrite 1000 ms default delay
            ttl_delayed: 10000      # overwrite 5000 ms default delay
        subdefCreation:           # this Q is "delayable" in case of record is locked
            ttl_delayed: 10000      # overwrite 5000 ms default delay
        pullAssets:
            ttl_retry: 5000
            max_retry : 5
```

ensuite j'ai lancé la commande 
`bin/console compile:configuration`
j'ai l'erreur suivante
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: Illegal string offset 'name' in /var/www/Phraseanet/lib/Alchemy/Phrasea/Core/Provider/WorkerConfigurationServiceProvider.php:60
Stack trace:
#0 /var/www/Phraseanet/lib/Alchemy/Phrasea/Core/Provider/WorkerConfigurationServiceProvider.php(60): Symfony\Component\Debug\ErrorHandler->handleError(2, 'Illegal string ...', '/var/www/Phrase...', 60, Array)
#1 /var/www/Phraseanet/vendor/pimple/pimple/lib/Pimple.php(126): Alchemy\Phrasea\Core\Provider\WorkerConfigurationServiceProvider->Alchemy\Phrasea\Core\Provider\{closure}(Object(Alchemy\Phrasea\CLI))
#2 /var/www/Phraseanet/vendor/pimple/pimple/lib/Pimple.php(83): Pimple::{closure}(Object(Alchemy\Phrasea\CLI))
#3 /var/www/Phraseanet/vendor/alchemy/queue-bundle/src/QueueProvider/QueueServiceProvider.php(34): Pimple->offsetGet('alchemy_queues....')
#4 /var/www/Phraseanet/vendor/silex/silex/src/Silex/Application.php(197): Alchemy\QueueProvider\QueueServiceProvider->boot(Object(Alchemy\Phrasea\CLI in /var/www/Phraseanet/lib/Alchemy/Phrasea/Core/Provider/WorkerConfigurationServiceProvider.php on line 60

```

**Comment by nmaillat** [comment]
Pouvez verifier la  validité de la syntaxe yaml de votre fichier de configuration.
Vous pouvez aussi  supprimer la section queues, celle ci sera automatiquement régénérée en vous rendant dans l'admin dans la section worker manager.

**Comment by pnrm** [comment]
Concernant la l'admin je n'y ai plus acces j'ai une erreur 500
J'ai vérifié la syntaxe du fichier yaml c'est valide
Par contre si je retire la section queue je laisse simplement ?
`workers :`

**Comment by nmaillat** [comment]
Concernant votre erreur 500 pouvez vous indiquez le message précis 
retourné Par Phraseanet dans logs/app_error-2021-01-01.log


Concernant la configuration oui juste le noeud 
`workers : `

Votre configuration doit alors ressembler a ça 
 Phraseanet appliquera alors les valeurs de TTL par default pour chacune des files de message.

```
video-editor:
    ChapterVttFieldName: VideoTextTrackChapters
    seekBackwardStep: 500
    seekForwardStep: 500
    playbackRates:
        - 1
        - '1.5'
        - 3
workers:
    queue:
        worker-queue:
            registry: alchemy_worker.queue_registry
            host: rabbitmq
            port: 5672
            user: 
            password: 
            vhost: /
externalservice:
    ginger:
        AutoSubtitling:
            service_base_url: 'https://base.uri'
            token: 
            transcript_format: text/vtt
            subdef_source: preview
```

si vous modifié dans l'admin un TTL de files de message il est important supprimer la file de message ainsi que les files attenantes 
eg :   

```
/vhost | subdefCreation | D DLX DLK | idle | 0 | 0 | 0 | 0.00/s | 0.00/s | 0.00/s
/vhost | subdefCreation_delayed | D TTL DLX DLK | idle | 0 | 0 | 0 | 0.00/s | 0.00/s | 0.00/s
/vhost | subdefCreation_failed | D TTL | idle | 0 | 0 | 0 |   |   |  
/vhost | subdefCreation_retry
```

**Comment by pnrm** [comment]
Voici le message dans le fichier log de Phraseanet
```
[2021-04-12 09:48:25] phraseanet.ERROR: Warning: Illegal string offset 'name' {"code":0,"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"/var/www/Phraseanet/lib/Alchemy/Phrasea/Core/Provider/WorkerConfigurationServiceProvider.php","line":60,"args":[]},{"namespace":"Symfony\\Component\\Debug","short_class":"ErrorHandler","class":"Symfony\\Component\\Debug\\ErrorHandler","type":"->","function":"handleError","file":"/var/www/Phraseanet/lib/Alchemy/Phrasea/Core/Provider/WorkerConfigurationServiceProvider.php","line":60,"args":[["string","2"],["string","Illegal string offset 'name'"],["string","/var/www/Phraseanet/lib/Alchemy/Phrasea/Core/Provider/WorkerConfigurationServiceProvider.php"],["string","60"],["array",{"app":["object","Alchemy\\Phrasea\\Application"],"defaultConfiguration":["array",{"worker-queue":["array",{"registry":["string","alchemy_worker.queue_registry"],"host":["string","localhost"],"port":["string","5672"],"user":["string","guest"],"password":["string","guest"],"vhost":["string","/"]}]}],"configuration":["object","Alchemy\\Phrasea\\Core\\Configuration\\PropertyAccess"],"queueConfigurations":["array",{"worker-queue":["null",null],"registry":["string","alchemy_worker.queue_registry"],"host":["string","localhost"],"port":["string","5672"],"user":["string","guest"],"password":["string","guest"],"vhost":["string","/"]}],"config":["array",{"worker-queue":["array",{"name":["string","worker-queue"]}]}],"queueConfiguration":["string","alchemy_worker.queue_registry"],"name":["string","registry"],"queueKey":["string","registry"]}]]},{"namespace":"Alchemy\\Phrasea\\Core\\Provider","short_class":"WorkerConfigurationServiceProvider","class":"Alchemy\\Phrasea\\Core\\Provider\\WorkerConfigurationServiceProvider","type":"->","function":"Alchemy\\Phrasea\\Core\\Provider\\{closure}","file":"/var/www/Phraseanet/vendor/pimple/pimple/lib/Pimple.php","line":126,"args":[["object","Alchemy\\Phrasea\\Application"]]},{"namespace":"","short_class":"Pimple","class":"Pimple","type":"::","function":"{closure}","file":"/var/www/Phraseanet/vendor/pimple/pimple/lib/Pimple.php","line":83,"args":[["object","Alchemy\\Phrasea\\Application"]]},{"namespace":"","short_class":"Pimple","class":"Pimple","type":"->","function":"offsetGet","file":"/var/www/Phraseanet/vendor/alchemy/queue-bundle/src/QueueProvider/QueueServiceProvider.php","line":34,"args":[["string","alchemy_queues.queues"]]},{"namespace":"Alchemy\\QueueProvider","short_class":"QueueServiceProvider","class":"Alchemy\\QueueProvider\\QueueServiceProvider","type":"->","function":"boot","file":"/var/www/Phraseanet/vendor/silex/silex/src/Silex/Application.php","line":197,"args":[["object","Alchemy\\Phrasea\\Application"]]},{"namespace":"Silex","short_class":"Application","class":"Silex\\Application","type":"->","function":"boot","file":"/var/www/Phraseanet/vendor/silex/silex/src/Silex/Application.php","line":577,"args":[]},{"namespace":"Silex","short_class":"Application","class":"Silex\\Application","type":"->","function":"handle","file":"/var/www/Phraseanet/vendor/silex/silex/src/Silex/Application.php","line":563,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]},{"namespace":"Silex","short_class":"Application","class":"Silex\\Application","type":"->","function":"run","file":"/var/www/Phraseanet/www/index.php","line":23,"args":[]}]} {"url":"/","ip":"192.168.10.154","http_method":"GET","server":"192.168.10.43","referrer":null}
```

**Comment by nmaillat** [comment]
Pouvez vous nous faire parvenir l'intégralité de votre fichier de configuration en supprimant les mots de passes et token a info@alchemy.fr
merci

**Comment by pnrm** [comment]
Merci à l'équipe d'alchemy
Erreur 500 résolue en supprimant le fichier compilé configuration-compiled.php et en relancant la compilation
Le taskmanager est désactivé pour utiliser le module worker
Par contre je n'arrive plus a éditer les métadatas et les vignettes ne se génèrent plus.
![image](https://user-images.githubusercontent.com/18323883/117690861-957e1180-b1bb-11eb-921e-5ba970a20556.png)
![image](https://user-images.githubusercontent.com/18323883/117690954-ae86c280-b1bb-11eb-95aa-85eb75ff82dd.png)

**Comment by pnrm** [comment]
Bascule sous une nouvelle instance de Phraseanet sous docker
