### ISSUE TITLE
phraseanet-phraseanet Container keeps restarting on fresh install

### ISSUE THREAD

**Issue by MechaKaradi** [alchemy-fr/Phraseanet#3977]
Using a fresh docker-compose file and following the instructons given in the wiki. Getting the following error on running the `docker-compose up -d` command from the phrasenet container.

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: Cannot use a scalar value as an array in /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Cache/Manager.php:104

Stack trace:

#0 /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Cache/Manager.php(104): Symfony\Component\Debug\ErrorHandler->handleError(2, 'Cannot use a sc...', '/var/alchemy/Ph...', 104, Array)

#1 /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Cache/Manager.php(91): Alchemy\Phrasea\Cache\Manager->register('redis', 'cache')

#2 /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Core/Provider/CacheServiceProvider.php(48): Alchemy\Phrasea\Cache\Manager->factory('cache', 'redis', Array)

#3 /var/alchemy/Phraseanet/vendor/pimple/pimple/lib/Pimple.php(126): Alchemy\Phrasea\Core\Provider\CacheServiceProvider->Alchemy\Phrasea\Core\Provider\{closure}(Object(Alchemy\Phrasea\CLI))

#4 /var/alchemy/Phraseanet/vendor/pimple/pimple/lib/Pimple.php(83): Pimple::{closure}(Object(Alchemy\Phrasea\CLI))

#5 /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Core/Provider/ in /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Cache/Manager.php on line 104
```

**Comment by MechaKaradi** [comment]
Hey,
The error is in the container called ```phraseanet```. 

It keeps crashing with the following error:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: Cannot use a scalar value as an array in /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Cache/Manager.php:104
Stack trace:
#0 /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Cache/Manager.php(104): Symfony\Component\Debug\ErrorHandler->handleError(2, 'Cannot use a sc...', '/var/alchemy/Ph...', 104, Array)
#1 /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Cache/Manager.php(91): Alchemy\Phrasea\Cache\Manager->register('redis', 'cache')
#2 /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Core/Provider/CacheServiceProvider.php(48): Alchemy\Phrasea\Cache\Manager->factory('cache', 'redis', Array)
#3 /var/alchemy/Phraseanet/vendor/pimple/pimple/lib/Pimple.php(126): Alchemy\Phrasea\Core\Provider\CacheServiceProvider->Alchemy\Phrasea\Core\Provider\{closure}(Object(Alchemy\Phrasea\CLI))
#4 /var/alchemy/Phraseanet/vendor/pimple/pimple/lib/Pimple.php(83): Pimple::{closure}(Object(Alchemy\Phrasea\CLI))
#5 /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Core/Provider/ in /var/alchemy/Phraseanet/lib/Alchemy/Phrasea/Cache/Manager.php on line 104
```
Attaching the config file 
On 15-03-2022 18:54:40, moctardiouf ***@***.***> wrote:
Hello, can you please explain us which container is generating this error. Can you show us the content of you local configuration.yml file.
Best regards

**Comment by moctardiouf** [comment]
Hello,

Think you for the informations. Can you please give us your configuration file. no attachment seen.

Seems like the matter is due to redis configuration.

**Comment by MechaKaradi** [comment]
Hey, seems GitHub isn't accepting a yml attachment. 

Please find the contents of the file in the pastebin below

https://pastebin.com/5tevqBbV

**Comment by MechaKaradi** [comment]
Hi, any feedback?
